package handler

const (
	CallbackBuy           = "buy"
	CallbackPlan          = "plan"
	CallbackSell          = "sell"
	CallbackDirect        = "direct"
	CallbackStart         = "start"
	CallbackConnect       = "connect"
	CallbackPayment       = "payment"
	CallbackTrial         = "trial"
	CallbackActivateTrial = "activate_trial"
	CallbackReferral      = "referral"
	CallbackProfile       = "profile"
	CallbackMyLinks       = "my_links"
	CallbackGuides        = "guides"
	CallbackGuideHowTo    = "guide_how_to_connect"
	CallbackAdminNotify   = "admin_notify"
	CallbackAdminNotifyAll   = "admin_notify_all"
	CallbackAdminNotifyDirect = "admin_notify_direct"
	CallbackAdminTools    = "admin_tools"
	CallbackAdminToolsResetDiamonds = "admin_tools_reset_diamonds"
	CallbackAdminToolsResetDiamondsConfirm = "admin_tools_reset_diamonds_confirm"
	CallbackAdminToolsSync = "admin_tools_sync"
	CallbackAdminToolsStats = "admin_tools_stats"
)
