package handler

const (
	CallbackBuy           = "buy"
	CallbackPlan          = "plan"
	CallbackSell          = "sell"
	CallbackDirect        = "direct"
	CallbackStart         = "start"
	CallbackConnect       = "connect"
	CallbackPayment       = "payment"
	CallbackTrial         = "trial"
	CallbackActivateTrial = "activate_trial"
	CallbackReferral      = "referral"
	CallbackProfile       = "profile"
	CallbackMyLinks       = "my_links"
	CallbackGuides        = "guides"
	CallbackGuideHowTo    = "guide_how_to_connect"
	CallbackAdminNotify   = "admin_notify"
	CallbackAdminNotifyAll   = "admin_notify_all"
	CallbackAdminNotifyDirect = "admin_notify_direct"
	CallbackAdminTools    = "admin_tools"
	CallbackAdminToolsResetDiamonds = "admin_tools_reset_diamonds"
	CallbackAdminToolsResetDiamondsConfirm = "admin_tools_reset_diamonds_confirm"
	CallbackAdminToolsSync = "admin_tools_sync"
	CallbackAdminToolsStats = "admin_tools_stats"
	CallbackAdminToolsDownloadDB = "admin_tools_download_db"
	CallbackLanguage = "language"
	CallbackLanguageSelectPrefix = "lang:"
	CallbackAdminPricing = "admin_pricing"
	CallbackAdminPricingDiscounts = "admin_pricing_discounts"
	CallbackAdminSubscriptionManage = "admin_subscription_manage"
	CallbackAdminSubscriptionActionPrefix = "admin_subscription_action"
	CallbackAdminSubscriptionDurationPrefix = "admin_subscription_duration"
	CallbackAdminDiscountScopePrefix = "admin_discount_scope"
	CallbackAdminDiscountDurationPrefix = "admin_discount_duration"
	CallbackAdminDiscountPercentPrefix = "admin_discount_percent"
	CallbackAdminDiscountFlush = "admin_discount_flush"
)
